// <auto-generated />
// Localização: Rascunho/Migrations/20260326000001_AddListaEspera.cs
// Feature #3 — Lista de Espera de Turmas (Waitlist)
//
// O que esta migration faz:
//   1. Cria a tabela ListasEspera com posição, status e prazo de confirmação.
//   2. Cria índices para buscas frequentes: (TurmaId, AlunoId), (TurmaId, Status, Posicao).
//   3. Adiciona as chaves estrangeiras para Turmas e Usuarios.
//
// NOTA sobre a tabela Interesses:
//   A relação Turma → Interesse (ICollection<Interesse> ListaDeEspera) foi removida
//   da entidade Turma. No banco, o FK FK_Interesses_Turmas_TurmaId permanece intacto
//   — EF Core só removeu a navegação explícita do lado Turma. Nenhum DROP de FK é
//   necessário pois a constraint em si não mudou de nome.
//   A tabela Interesses será mantida para uso futuro no Feature #10.

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Rascunho.Migrations
{
    /// <inheritdoc />
    public partial class AddListaEspera : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ListasEspera",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    TurmaId = table.Column<int>(type: "integer", nullable: false),
                    AlunoId = table.Column<int>(type: "integer", nullable: false),
                    DataEntrada = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Posicao = table.Column<int>(type: "integer", nullable: false),
                    Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    DataNotificacao = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    DataExpiracao = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ListasEspera", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ListasEspera_Turmas_TurmaId",
                        column: x => x.TurmaId,
                        principalTable: "Turmas",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ListasEspera_Usuarios_AlunoId",
                        column: x => x.AlunoId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // Índice para busca por aluno (minhas esperas)
            migrationBuilder.CreateIndex(
                name: "IX_ListasEspera_AlunoId",
                table: "ListasEspera",
                column: "AlunoId");

            // Índice para unicidade por (turma, aluno)
            migrationBuilder.CreateIndex(
                name: "IX_ListasEspera_TurmaId_AlunoId",
                table: "ListasEspera",
                columns: new[] { "TurmaId", "AlunoId" });

            // Índice para busca do próximo na fila (turma, status, posição)
            migrationBuilder.CreateIndex(
                name: "IX_ListasEspera_TurmaId_Status_Posicao",
                table: "ListasEspera",
                columns: new[] { "TurmaId", "Status", "Posicao" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ListasEspera");
        }
    }
}
