// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rascunho.Data;

#nullable disable

namespace Rascunho.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310164556_InitialCreateInt")]
    partial class InitialCreateInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rascunho.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Tipo").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Rascunho.Entities.Aluno", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("Rascunho.Entities.Bolsista", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Bolsista");
                });

            modelBuilder.Entity("Rascunho.Entities.Gerente", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("Rascunho.Entities.Lider", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Líder");
                });

            modelBuilder.Entity("Rascunho.Entities.Professor", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("Rascunho.Entities.Recepcao", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Recepção");
                });
#pragma warning restore 612, 618
        }
    }
}
