// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rascunho.Data;

#nullable disable

namespace Rascunho.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313192102_AdicionandoChamadas")]
    partial class AdicionandoChamadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rascunho.Entities.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TipoVisibilidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Avisos", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.HabilidadeUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RitmoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PapelDominante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId", "RitmoId");

                    b.HasIndex("RitmoId");

                    b.ToTable("HabilidadesUsuarios", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Interesse", b =>
                {
                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TurmaId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Interesses", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Matricula", b =>
                {
                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TurmaId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.RegistroPresenca", b =>
                {
                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataAula")
                        .HasColumnType("date");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("TurmaId", "AlunoId", "DataAula");

                    b.HasIndex("AlunoId");

                    b.ToTable("RegistrosPresencas", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Ritmo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Ritmos", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Salas", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaDaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("interval");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("integer");

                    b.Property<string>("LinkWhatsApp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RitmoId")
                        .HasColumnType("integer");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RitmoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.TurmaProfessor", b =>
                {
                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("TurmaId", "ProfessorId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("TurmaProfessores", (string)null);
                });

            modelBuilder.Entity("Rascunho.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Tipo").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Rascunho.Entities.Aluno", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("Rascunho.Entities.Bolsista", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Bolsista");
                });

            modelBuilder.Entity("Rascunho.Entities.Gerente", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("Rascunho.Entities.Lider", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Líder");
                });

            modelBuilder.Entity("Rascunho.Entities.Professor", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("Rascunho.Entities.Recepcao", b =>
                {
                    b.HasBaseType("Rascunho.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Recepção");
                });

            modelBuilder.Entity("Rascunho.Entities.Aviso", b =>
                {
                    b.HasOne("Rascunho.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Rascunho.Entities.HabilidadeUsuario", b =>
                {
                    b.HasOne("Rascunho.Entities.Ritmo", "Ritmo")
                        .WithMany()
                        .HasForeignKey("RitmoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ritmo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rascunho.Entities.Interesse", b =>
                {
                    b.HasOne("Rascunho.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Turma", "Turma")
                        .WithMany("ListaDeEspera")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Rascunho.Entities.Matricula", b =>
                {
                    b.HasOne("Rascunho.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Rascunho.Entities.RegistroPresenca", b =>
                {
                    b.HasOne("Rascunho.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Rascunho.Entities.Turma", b =>
                {
                    b.HasOne("Rascunho.Entities.Ritmo", "Ritmo")
                        .WithMany()
                        .HasForeignKey("RitmoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ritmo");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Rascunho.Entities.TurmaProfessor", b =>
                {
                    b.HasOne("Rascunho.Entities.Usuario", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rascunho.Entities.Turma", "Turma")
                        .WithMany("Professores")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Rascunho.Entities.Turma", b =>
                {
                    b.Navigation("ListaDeEspera");

                    b.Navigation("Matriculas");

                    b.Navigation("Professores");
                });
#pragma warning restore 612, 618
        }
    }
}
