server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
        application/octet-stream clr;
        application/octet-stream pdb;
        application/font-woff woff;
        application/font-woff2 woff2;
    }

    # --- ADICIONE ESTA NOVA REGRA AQUI ---
    # Ela garante que o navegador sempre encontre o mapa de arquivos atualizado!
    location /_framework/blazor.boot.json {
        try_files $uri =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # O Resto se mantém igual:
    location / {
        try_files $uri $uri/ /index.html =404;
    }

    location /_framework/ {
        try_files $uri =404;
    }
}