name: Deploy Automático para Produção (VPS)

on:
  push:
    branches: [ "main" ]

jobs:
  # =========================================================
  # FASE 1: CONSTRUIR E GUARDAR AS IMAGENS NO GHCR.IO
  # =========================================================
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Fazer login no GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Construir e Enviar a Imagem da API (Backend)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/obrandemburg/rascunho:latest

      - name: Construir e Enviar a Imagem do Frontend (Blazor WebAssembly)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.Client
          push: true
          tags: ghcr.io/obrandemburg/rascunho-client:latest

  # =========================================================
  # FASE 2: ENTRAR NA VPS E ATUALIZAR O SISTEMA
  # =========================================================
  deploy:
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Conectar na VPS via SSH e Atualizar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}    # <--- CORRIGIDO PARA O SEU SECRET EXATO
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22                             # Deixamos chumbado na porta padrão SSH
          script: |
            # 1. Navega até a pasta do seu projeto na VPS
            cd /home/usuario/pontodadanca
            
            # 2. Faz login no ghcr.io de dentro da VPS
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 3. Baixa as imagens novas que a Fase 1 acabou de criar
            docker compose pull
            
            # 4. Reinicia os contêineres aplicando as novidades
            docker compose up -d